--- https://docs.snowflake.com/en/sql-reference/functions/parse_document-snowflake-cortex

CREATE OR REPLACE PROCEDURE DEMO.DEMO.PARSEDOCS(FILENAME STRING)
RETURNS TABLE ("PARSEDDOC" VARCHAR )
LANGUAGE SQL
EXECUTE AS OWNER
AS 
DECLARE
  res RESULTSET;
BEGIN
  ALTER STAGE DOCUMENTS REFRESH; 
  res := ( SELECT TO_VARCHAR(SNOWFLAKE.CORTEX.PARSE_DOCUMENT(@DOCUMENTS, :FILENAME)) as PARSEDDOC );
  RETURN TABLE(res);
END;

call DEMO.DEMO.PARSEDOCS('${pdffile}');


CREATE OR REPLACE TABLE PARSEDCONTENT (
	content_id NUMBER(38,0) primary key autoincrement start 1 increment 1 noorder,
	content VARCHAR(16777216),
    metadata VARCHAR(16777216)
);

desc table PARSEDCONTENT;

select * from PARSEDCONTENT;

