--- https://docs.snowflake.com/en/sql-reference/functions/parse_document-snowflake-cortex

CREATE OR REPLACE PROCEDURE DEMO.DEMO.PARSEDOCS(FILENAME STRING)
RETURNS TABLE ("PARSEDDOC" VARCHAR )
LANGUAGE SQL
EXECUTE AS OWNER
AS 
DECLARE
  res RESULTSET;
BEGIN
  ALTER STAGE DOCUMENTS REFRESH; 
  res := ( SELECT TO_VARCHAR(SNOWFLAKE.CORTEX.PARSE_DOCUMENT(@DOCUMENTS, :FILENAME)) as PARSEDDOC );
  RETURN TABLE(res);
END;

call DEMO.DEMO.PARSEDOCS('${pdffile}');

