--- https://docs.snowflake.com/en/sql-reference/functions/parse_document-snowflake-cortex

CREATE OR REPLACE PROCEDURE DEMO.DEMO.PARSEDOCS(FILENAME STRING)
RETURNS TABLE ("PARSEDDOC" VARCHAR )
LANGUAGE SQL
EXECUTE AS OWNER
AS 
DECLARE
  res RESULTSET;
BEGIN
  ALTER STAGE DOCUMENTS REFRESH; 
  res := ( SELECT TO_VARCHAR(SNOWFLAKE.CORTEX.PARSE_DOCUMENT(@DOCUMENTS, :FILENAME)) as PARSEDDOC );
  RETURN TABLE(res);
END;

call DEMO.DEMO.PARSEDOCS('${pdffile}');


CREATE OR REPLACE TABLE PARSEDCONTENT (
	content_id NUMBER(38,0) primary key autoincrement start 1 increment 1 noorder,
	content VARCHAR(16777216),
    metadata VARCHAR(16777216)
);

desc table PARSEDCONTENT;

select * from PARSEDCONTENT;

CREATE OR REPLACE WAREHOUSE CORTEX_SEARCH_AQ_WH
WITH
     WAREHOUSE_SIZE='X-SMALL'
     AUTO_SUSPEND = 120
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED=TRUE;
     

CREATE OR REPLACE CORTEX SEARCH SERVICE DEMO.DEMO.AIRQUALITY_SRVC
ON AIRQUALITY_TEXT
ATTRIBUTES REPORTINGAREA, STATECODE, LATITUDE, LONGITUDE, DATEOBSERVED, PARAMETERNAME, AQI
WAREHOUSE = CORTEX_SEARCH_AQ_WH
TARGET_LAG = '1 hour'
AS
        SELECT DATEOBSERVED,HOUROBSERVED,REPORTINGAREA, STATECODE, LATITUDE, LONGITUDE,PARAMETERNAME,AQI,
        ('Air Quality Report for ' || REPORTINGAREA || ' ' || STATECODE  || ' of ' ||  PARAMETERNAME || ' is ' || AQI || ' which is ' || CATEGORYNAME || '.  Observation date/time was ' || DATEOBSERVED || ' at the hour of ' || HOUROBSERVED  || '.\n\n' ) as AIRQUALITY_TEXT
    FROM DEMO.DEMO.AQ;


    DESC CORTEX SEARCH SERVICE DEMO.DEMO.AIRQUALITY_SRVC;
    GRANT USAGE ON CORTEX SEARCH SERVICE DEMO.DEMO.AIRQUALITY_SRVC TO ROLE ACCOUNTADMIN;
    
SELECT *
FROM
  TABLE (
    CORTEX_SEARCH_DATA_SCAN (
      SERVICE_NAME => 'AIRQUALITY_SRVC'
    )
  ) LIMIT 5 ;

  SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      'DEMO.DEMO.AIRQUALITY_SRVC',
      '{
        "query": "PM10 is Good",
        "columns":[
            "AIRQUALITY_TEXT",
            "REPORTINGAREA",
            "STATECODE",
            "DATEOBSERVED",
            "HOUROBSERVED",
            "PARAMETERNAME",
            "AQI"
        ],
        "filter": {"@eq": {"REPORTINGAREA": "Boston"} },
        "limit":10
      }'
  )
)['results'] as results;

    
        SELECT DATEOBSERVED,HOUROBSERVED,REPORTINGAREA, STATECODE, LATITUDE, LONGITUDE,
        ('Air Quality Report for ' || REPORTINGAREA || ' ' || STATECODE  || ' of ' ||  PARAMETERNAME || ' is ' || AQI || ' which is ' || CATEGORYNAME || '.  Observation date/time was ' || DATEOBSERVED || ' at the hour of ' || HOUROBSERVED  || '.\n\n' ) as AIRQUALITY_TEXT
    FROM DEMO.DEMO.AQ where STATECODE = 'MA';





